[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/load"
  to = "/.netlify/functions/load"
  status = 200

[[redirects]]
  from = "/save"
  to = "/.netlify/functions/save"
  status = 200

[[redirects]]
  from = "/reset"
  to = "/.netlify/functions/reset"
  status = 200

[[redirects]]
  from = "/sync"
  to = "/.netlify/functions/sync"
  status = 200
